# Generated by Django 4.2.30 on 2026-08-30 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên thương hiệu')),
                ('slug', models.SlugField(blank=True, max_length=130, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Thương hiệu',
                'verbose_name_plural': 'Thương hiệu',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon đại diện')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục sản phẩm',
                'verbose_name_plural': 'Danh mục sản phẩm',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã SKU')),
                ('main_image_url', models.URLField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá bán niêm yết')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá gốc thị trường')),
                ('stock', models.PositiveIntegerField(default=100, verbose_name='Số lượng tồn kho')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='Số lượng đã bán')),
                ('is_fast_delivery_1h', models.BooleanField(default=True, verbose_name='Giao 1h')),
                ('gift_description', models.CharField(blank=True, max_length=255, verbose_name='Quà tặng kèm')),
                ('age_group', models.CharField(choices=[('ALL', 'Mọi độ tuổi'), ('0_1', '0 - 1 tuổi'), ('1_2', '1 - 2 tuổi'), ('2_PLUS', 'Trên 2 tuổi'), ('MOM', 'Mẹ bầu & Sau sinh')], default='ALL', max_length=20, verbose_name='Độ tuổi phù hợp')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='Xuất xứ')),
                ('description', models.TextField(blank=True, verbose_name='Chi tiết sản phẩm')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Đánh giá sao')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Lượt đánh giá')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Số sao (1-5)')),
                ('comment', models.TextField(verbose_name='Nội dung đánh giá / Feedback')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Duyệt hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đánh giá & Feedback',
                'verbose_name_plural': 'Quản lý Đánh giá & Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='brands', to='products.category'),
        ),
    ]
