# Generated by Django 4.2.30 on 2026-08-30 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=30, unique=True, verbose_name='Mã đơn')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Người nhận')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('shipping_address', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('city', models.CharField(default='TP. Hồ Chí Minh', max_length=100)),
                ('district', models.CharField(default='Quận 1', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('shipping_method', models.CharField(choices=[('FAST_1H', 'Giao Siêu Tốc 1h'), ('STANDARD', 'Giao tiêu chuẩn (1-2 ngày)')], default='FAST_1H', max_length=30)),
                ('payment_method', models.CharField(choices=[('COD', 'Thanh toán tiền mặt (COD)'), ('VNPAY', 'Ví VNPAY / Ngân hàng QR'), ('MOMO', 'Ví MoMo')], default='COD', max_length=30)),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('PROCESSING', 'Đã xác nhận & Đang chuẩn bị'), ('SHIPPING', 'Đang giao hàng (Siêu tốc 1h)'), ('DELIVERED', 'Đã giao hàng thành công'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên xử lý')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
