# Generated by Django 4.2.30 on 2026-08-30 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('STAFF', 'Nhân viên tư vấn & bán hàng'), ('ADMIN', 'Quản trị viên')], default='CUSTOMER', max_length=20, verbose_name='Vai trò')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('baby_birth_date', models.DateField(blank=True, null=True, verbose_name='Ngày sinh bé / Ngày dự sinh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày trực')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Giờ Check-in')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Giờ Check-out')),
                ('orders_processed_count', models.PositiveIntegerField(default=0, verbose_name='Số đơn xử lý trong ca')),
                ('revenue_generated', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Doanh thu ca trực (VNĐ)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú ca trực')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Ca trực nhân viên',
                'verbose_name_plural': 'Quản lý Check-in/Check-out nhân viên',
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=150, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('city', models.CharField(default='TP. Hồ Chí Minh', max_length=100, verbose_name='Tỉnh/Thành')),
                ('district', models.CharField(default='Quận 1', max_length=100, verbose_name='Quận/Huyện')),
                ('street_address', models.CharField(max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sổ địa chỉ',
                'verbose_name_plural': 'Sổ địa chỉ',
            },
        ),
    ]
