# Generated by Django 4.2.30 on 2026-08-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề Banner')),
                ('image', models.FileField(blank=True, null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('link_url', models.CharField(default='#', max_length=500, verbose_name='Đường dẫn đích')),
                ('position', models.CharField(choices=[('TOP_ANNOUNCEMENT', 'Thanh thông báo trên cùng'), ('HERO', 'Hero Slider chính'), ('SUB_HERO', 'Banner phụ cạnh Hero'), ('CATEGORY', 'Banner danh mục'), ('FOOTER', 'Banner chân trang')], default='HERO', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner quảng cáo',
                'verbose_name_plural': 'Banner quảng cáo',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='GIÁ SỐC MỖI NGÀY - DEAL CHỚP NHOÁNG', max_length=200, verbose_name='Tiêu đề Flash Sale')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc (Countdown)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sale',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền giảm (VNĐ)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Hoặc giảm theo % (0-100)')),
                ('min_order_value', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Đơn tối thiểu (VNĐ)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá sốc Flash Sale')),
                ('quantity_limit', models.PositiveIntegerField(default=50, verbose_name='Số lượng bán')),
                ('quantity_sold', models.PositiveIntegerField(default=15, verbose_name='Đã bán')),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotions.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='products.product')),
            ],
        ),
    ]
