# Generated by Django 4.2.30 on 2026-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên siêu thị')),
                ('province', models.CharField(default='TP. Hồ Chí Minh', max_length=100, verbose_name='Tỉnh / Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận / Huyện')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ cụ thể')),
                ('phone', models.CharField(default='1800 6609', max_length=20, verbose_name='Số điện thoại')),
                ('opening_hours', models.CharField(default='08:00 - 22:00 (Tất cả các ngày trong tuần)', max_length=100, verbose_name='Giờ mở cửa')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Siêu thị Con Cưng',
                'verbose_name_plural': 'Hệ thống 1164 Siêu thị',
                'ordering': ['province', 'district'],
            },
        ),
    ]
