# Generated by Django 4.2.30 on 2026-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_ai',
            field=models.BooleanField(default=False, verbose_name='Tin nhắn từ AI'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='suggested_products_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Danh sách SP gợi ý (JSON)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='chat_mode',
            field=models.CharField(choices=[('AI', 'Trợ lý AI Mẹ & Bé 24/7'), ('STAFF', 'Nhân viên CSKH trực tuyến')], default='AI', max_length=20, verbose_name='Chế độ Chat'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='customer_name',
            field=models.CharField(default='Khách hàng Con Cưng', max_length=150),
        ),
    ]
